baseURL = "https://blue-bird1.github.io"
languageCode = "zh-CN"
author = "blue bird"
title = "青鸟的博客"
theme = "github-style"
hasCJKLanguage = true
googleAnalytics = "UA-110301700-1"

# Syntax highlighting 
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
        contentType = "posts"
	    siteStartYear = 2017
        author = "bluebird"
        github =  "blue-bird1"
        twitter = "blue_bird__hc"
        description = "bluebird的博客" 
        avatar = "http://www.gravatar.com/avatar/36cc0b77102e4b4e776f444f95525703?s=512"
        motto = "code and security"

        [params.tags]
                enabled = true

        #Categories settings
        [params.categories]
                enabled = true




