baseURL = "https://blue-bird1.github.io/"
languageCode = "zh-CN"
title = "青鸟的博客"
theme = "hermit"
hasCJKLanguage = true
googleAnalytics = "UA-110301700-1"

# Syntax highlighting 
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsStyle = "pygments"
pygmentsOptions = "linenos=table"

#Enable Hugo Emoji Conversion
enableEmoji=true

[author]
author = "blue bird"

[taxonomies]
tag = "tags"

[markup]
  [markup.highlight]
    guessSyntax = true
    tabWidth = 4


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  code_copy_button = true 


[menu]

[[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

[[menu.main]]
    name = "About"
    url = "about/"
    weight = 20
[[menu.main]]
    name = "Friend"
    url = "friends/"
    weight = 20

[[params.social]]
  name = "github"
  url = "https://github.com/blue-bird1"

